<?php

/**
 * ProcessWire Color Inputfield
 *
 * @author Christoph Thelen aka @kixe 2017/07/03
 * @copyright © 2017 Christoph Thelen
 * @license Licensed under GNU/GPL v3
 * @link https://processwire.com/talk/topic/...
 * @version 1.0.5
 * @since 1.0.1 2017/07/05 - better validation, spectrum options modifiable
 * @since 1.0.2 2017/07/09 - added default value option
 * @since 1.0.3 2017/07/09 - added option for custom javascript
 * @since 1.0.4 2017/08/18 - made # optional for input (pattern attribute)
 * @since 1.0.5 2017/08/28 - optimized default color handling, added output format option array()
 * 
 * made for ProcessWire 2.x, 3.x, Copyright 2016 by Ryan Cramer
 * https://processwire.com
 * @todo
 * - include i18n support provided by spectrum color picker
 * 
 */

class InputfieldColor extends Inputfield {
	
	public static function getModuleInfo() {
		return array(
			'title' => __('Color', __FILE__), // Module Title
			'summary' => __('Inputfield for colors', __FILE__), // Module Summary
			'version' => 105,
			'href' => 'https://processwire.com/talk/topic/16679-fieldtypecolor/'
			);
	}

	/**
	 * Construct
	 * 
	 * @throws WireException
	 * 
	 */
	public function __construct() {
		parent::__construct();
		$this->set('icon', 'paint-brush');
		$this->setAttribute('type', 'text'); 
		$this->setAttribute('size', 10); 
		$this->setAttribute('placeholder', '#000000');
		$this->setAttribute('pattern', '(#?[a-fA-F\d]{6})?');
	}

	public function init() {
		$this->inputType = 0;
		$this->spectrum =  '';
		$this->initJS = '';
		$this->fileJS = '';
		$this->fileCSS = '';
		$this->jqueryCore = 0;
		$this->jqueryUI = 0;
		$this->alpha = 0;
		parent::init();
	}

	/**
	 * Called before the render method
	 * checking for SpectrumColorPicker
	 * 
	 * @param Inputfield $parent
	 * @param bool $renderValueMode
	 * @return $this
	 *
	 */
	public function renderReady(Inputfield $parent = null, $renderValueMode = false) {
		$url = $this->config->urls->get('InputfieldColor');
		switch ($this->inputType) {	
			case 3:
				$this->wire('modules')->get('JqueryCore');
				$this->config->scripts->add($url . 'spectrum/spectrum.js');
				$this->config->styles->add($url . 'spectrum/spectrum.css');
				break;
			case 4:
				if ($this->jqueryCore) $this->wire('modules')->get('JqueryCore');
				if ($this->jqueryUI) $this->wire('modules')->get('JqueryUI');
				if ($this->fileJS) $this->config->scripts->add($url . $this->fileJS);
				if ($this->fileCSS) $this->config->styles->add($url . $this->fileCSS);
			break;
		}
		parent::renderReady($parent, $renderValueMode); 
	}

	public function ___render() {
		if ($this->value === "" && strlen($this->initValue)) $this->value = $this->initValue;
		if (!$this->value) $this->value = null;

		if ($this->value) {
			$color32 = "#".$this->value;
			$color24 = $bgColor = "#".substr($this->value,2,6);		
			$value = array_map('hexdec', str_split($this->value, 2));
		} else {
			$color32 = $color24 = null;
			$value = array(255,255,255,255);
			$bgColor = '#fff';
		}

		$opacity = round($value[0] / 255, 2);
		$textColor = ($value[1]+6*$value[2]+$value[3])*3/8 > 460? '#000':'#fff';
		$rgba = "rgba($value[1], $value[2], $value[3], $opacity)";
		$this->attr('value', $color24);

		switch ($this->inputType) {	
			case 0:		
				$this->attr('type', 'color');
				break;
			case 1:
				$this->attr('style', "color: $textColor; background: $bgColor;");
				break;
			case 2:
				$this->alpha = 1;
				if ($opacity < 0.45) $textColor = '#000';
				$this->attr('value', $color32);
				$this->attr('style', "color: $textColor; background: $bgColor; background-image: linear-gradient($rgba, $rgba), url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAGUlEQVQYV2M4gwH+YwCGIasIUwhT25BVBADtzYNYrHvv4gAAAABJRU5ErkJggg==');");
				$this->attr('placeholder', '#ff000000');
				$this->attr('pattern', '(#?[a-fA-F\d]{8})?');
				break;
			case 3:
				$this->alpha = 1;
				if (!$color32) $color32 = '#00000000';
				$this->attr('value', $color32);
				$this->attr('placeholder', '#ff000000');
				$this->attr('pattern', '(#?[a-fA-F\d]{8})?');
				break;
			case 4:
				if ($this->alpha) $this->attr('value', $color32);
				else $this->attr('value', $color24);
				break;			
		}

		$attrs = $this->getAttributes();

		$out = "<input " . $this->getAttributesString($attrs) . " />";
		if( $this->inputType == 3) {
			$options = $this->spectrum? str_replace(array(",\n","\n"),", ", trim($this->spectrum,",\t\n\r\0\x0B")).',' : '';
			$value = $color32? $color32 : null;
			$out .= "<script>
				$(\"#$this->id\").spectrum({
				    $options
				    color: \"$value\",
				    change: function(color) {
				    	this.value = color.toHex8String(); 
				    }
				});
			</script>
			";
		}
		if( $this->inputType == 4) {
			$value = $color32? $color32 : null;
			if ($this->initJS) {
				$initJS = str_replace(array("{value}","{id}"), array($color24, $this->id), $this->initJS);
				$out .= "<script>
					$initJS
				</script>
				";
			}
		}
		return $out; 
	}

	public function ___processInput(WireInputData $input) {
		parent::___processInput($input);
		$value = $this->attr('value');
		if (!$value) return $this;		
		$pattern = $this->alpha? '/#?[a-fA-F\d]{8}/' : '/#?[a-fA-F\d]{6}/';
		if(!preg_match($pattern, $value)) $this->error("Does not match required pattern: $pattern.");
		return $this;

	}

	public function getConfigInputfields() {
		$inputfields = parent::getConfigInputfields();

		$f = $this->wire('modules')->get('InputfieldRadios');
		$f->attr('name', 'inputType');
		$f->label = $this->_('Inputfieldtype'); 
		$f->addOption(0, $this->_('Inputfield type=\'color\' (HTML5 - limited browser support)')); 
		$f->addOption(1, $this->_('Inputfield type=\'text\' expects 24bit hexcode strings'));
		$f->addOption(2, $this->_('Inputfield type=\'text\' expects 32bit hexcode strings (alpha channel)'));  
		$f->addOption(3, $this->_('Inputfield with Spectrum Color Picker (JavaScript)')); 
		$f->addOption(4, $this->_('Inputfield type=\'text\' with custom JavaScript and/or CSS')); 
		$f->attr('value', $this->inputType);
		$f->description = $this->_('');
		$f->columnWidth = 50;
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldTextarea');
		$f->attr('name', 'spectrum');
		$f->attr('rows', 10);
		$f->label = $this->_('Color Picker Options'); 
		$f->attr('value', $this->spectrum);
		$f->description = $this->_('Set or modify options for the **Spectrum Color Picker**. [Read more ...](https://bgrins.github.io/spectrum/#options)');
		$f->notes = $this->_("One option per line in the format: 'option: value'. The options: 'color' and 'change' are used by the system and not modifiable.");
		$f->columnWidth = 50;
		$f->showIf = "inputType=3";
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldTextarea');
		$f->attr('name', 'initJS');
		$f->attr('rows', 3);
		$f->label = $this->_('Initial JS'); 
		$f->attr('value', $this->initJS);
		$f->description = $this->_('JavaScript code initiating your custom JS color picker. Use {id} and {value} as placeholders for the related field attributes in your selector');
		$f->notes = sprintf($this->_('{id} will be replaced by the string "%s"'), $this->id);
		$f->columnWidth = 33;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$rootUrl = $this->config->urls->get('InputfieldColor');

		$f = $this->wire('modules')->get('InputfieldURL');
		$f->attr('name', 'fileJS');
		$f->label = $this->_('Include JS File'); 
		$f->attr('value', $this->fileJS);
		$f->description = $this->_('Set the path to your custom JavaScript file.');
		$f->notes = sprintf($this->_('URL string relative to "%s"'), $rootUrl);
		$f->columnWidth = 34;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$f = $this->wire('modules')->get('InputfieldURL');
		$f->attr('name', 'fileCSS');
		$f->label = $this->_('Include CSS File'); 
		$f->attr('value', $this->fileCSS);
		$f->description = $this->_('Set the path to your custom stylesheet file.');
		$f->notes = sprintf($this->_('URL string relative to "%s"'), $rootUrl);
		$f->columnWidth = 33;
		$f->showIf = "inputType=4";
		$f->requiredIf = "inputType=4";
		$inputfields->add($f);

		$f = $this->modules->get('InputfieldCheckbox');
        $f->attr('name', 'jqueryCore'); 
        $f->label = __('Enable JqueryCore');
        $f->attr('checked', $this->jqueryCore ? 'checked' : '' );
        $f->columnWidth = 33; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

		$f = $this->modules->get('InputfieldCheckbox');
        $f->attr('name', 'jqueryUI'); 
        $f->label = __('Enable JqueryUI');
        $f->attr('checked', $this->jqueryUI ? 'checked' : '' );
        $f->columnWidth = 34; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

		$f = $this->modules->get('InputfieldRadios');
        $f->attr('name', 'alpha'); 
        $f->addOption(0, $this->_('6 digits "#ff0000"'));
        $f->addOption(1, $this->_('8 digits "#ffff0000" (leading alpha channel)'));
        $f->label = __('Select value type');
        $f->attr('value', $this->alpha);
        $f->columnWidth = 33; 
        $f->showIf = "inputType=4";
        $inputfields->append($f);

        return $inputfields; 
	}
}
